services:
  - type: web
    name: twofirstsonepup
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: twofirstsonepup-db
          property: connectionString

databases:
  - name: twofirstsonepup-db
    plan: free