services:
  - type: web
    name: twofirstsonepup
    runtime: python
    plan: free
    autoDeploy: true
    region: oregon            # or "frankfurt" etc.; optional
    healthCheckPath: /health  # FastAPI health endpoint

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      # Set these in the Render dashboard after the service is created
      - key: DATABASE_URL
        sync: false
      - key: SYNC_AUTH_TOKEN
        sync: false
