"""standing adjustments audit

Revision ID: 011954031709
Revises: a6c9ada56d9f
Create Date: 2026-06-07 22:10:14.913535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011954031709'
down_revision: Union[str, Sequence[str], None] = 'a6c9ada56d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standing_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=True),
    sa.Column('new_value', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standing_adjustments_league_id'), 'standing_adjustments', ['league_id'], unique=False)
    op.create_index(op.f('ix_standing_adjustments_manager_id'), 'standing_adjustments', ['manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standing_adjustments_manager_id'), table_name='standing_adjustments')
    op.drop_index(op.f('ix_standing_adjustments_league_id'), table_name='standing_adjustments')
    op.drop_table('standing_adjustments')
    # ### end Alembic commands ###
