"""keeper selections table

Revision ID: 01bdf4818e81
Revises: a2bae55c86ca
Create Date: 2026-06-07 17:08:07.431478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bdf4818e81'
down_revision: Union[str, Sequence[str], None] = 'a2bae55c86ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keeper_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('is_discovery', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'player_id', 'season_year', name='uq_keeper_sel_mgr_player_season')
    )
    op.create_index(op.f('ix_keeper_selections_league_id'), 'keeper_selections', ['league_id'], unique=False)
    op.create_index(op.f('ix_keeper_selections_manager_id'), 'keeper_selections', ['manager_id'], unique=False)
    op.create_index(op.f('ix_keeper_selections_player_id'), 'keeper_selections', ['player_id'], unique=False)
    op.create_index(op.f('ix_keeper_selections_season_year'), 'keeper_selections', ['season_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keeper_selections_season_year'), table_name='keeper_selections')
    op.drop_index(op.f('ix_keeper_selections_player_id'), table_name='keeper_selections')
    op.drop_index(op.f('ix_keeper_selections_manager_id'), table_name='keeper_selections')
    op.drop_index(op.f('ix_keeper_selections_league_id'), table_name='keeper_selections')
    op.drop_table('keeper_selections')
    # ### end Alembic commands ###
