"""draft picks season/type + trade pick fields

Revision ID: 22a39fde8712
Revises: 01bdf4818e81
Create Date: 2026-06-07 17:37:51.159136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a39fde8712'
down_revision: Union[str, Sequence[str], None] = '01bdf4818e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_picks', sa.Column('season_year', sa.Integer(), server_default='0', nullable=False))
    op.add_column('draft_picks', sa.Column('draft_type', sa.String(), server_default='main', nullable=False))
    op.create_index(op.f('ix_draft_picks_season_year'), 'draft_picks', ['season_year'], unique=False)
    op.add_column('trades', sa.Column('pick_season_year', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('pick_draft_type', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('pick_round', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('pick_original_manager', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'trades', 'managers', ['pick_original_manager'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'pick_original_manager')
    op.drop_column('trades', 'pick_round')
    op.drop_column('trades', 'pick_draft_type')
    op.drop_column('trades', 'pick_season_year')
    op.drop_index(op.f('ix_draft_picks_season_year'), table_name='draft_picks')
    op.drop_column('draft_picks', 'draft_type')
    op.drop_column('draft_picks', 'season_year')
    # ### end Alembic commands ###
