"""add matches table

Revision ID: 35930d54c10a
Revises: a37f83c0d9f5
Create Date: 2026-06-07 14:09:13.368670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35930d54c10a'
down_revision: Union[str, Sequence[str], None] = 'a37f83c0d9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('gameweek_id', sa.UUID(), nullable=False),
    sa.Column('home_manager_id', sa.UUID(), nullable=False),
    sa.Column('away_manager_id', sa.UUID(), nullable=False),
    sa.Column('home_points', sa.Integer(), nullable=True),
    sa.Column('away_points', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('finished', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['away_manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['home_manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gameweek_id', 'home_manager_id', 'away_manager_id', name='uq_match_gw_home_away')
    )
    op.create_index(op.f('ix_matches_away_manager_id'), 'matches', ['away_manager_id'], unique=False)
    op.create_index(op.f('ix_matches_gameweek_id'), 'matches', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_matches_home_manager_id'), 'matches', ['home_manager_id'], unique=False)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_manager_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_gameweek_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_manager_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
