"""future picks

Revision ID: 3cb37bde6dc6
Revises: 6ed426ddcfd3
Create Date: 2026-06-07 21:21:40.601184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb37bde6dc6'
down_revision: Union[str, Sequence[str], None] = '6ed426ddcfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_picks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('draft_type', sa.String(), server_default='main', nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('original_owner', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season_year', 'draft_type', 'round', 'original_owner', name='uq_future_pick')
    )
    op.create_index(op.f('ix_future_picks_league_id'), 'future_picks', ['league_id'], unique=False)
    op.create_index(op.f('ix_future_picks_season_year'), 'future_picks', ['season_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_future_picks_season_year'), table_name='future_picks')
    op.drop_index(op.f('ix_future_picks_league_id'), table_name='future_picks')
    op.drop_table('future_picks')
    # ### end Alembic commands ###
