"""keeper_seeds prior_years -> years_remaining

Revision ID: 4e14166e5308
Revises: f573357ce3ed
Create Date: 2026-06-07 21:56:36.382138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e14166e5308'
down_revision: Union[str, Sequence[str], None] = 'f573357ce3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keeper_seeds', sa.Column('years_remaining', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('keeper_seeds', 'prior_years')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keeper_seeds', sa.Column('prior_years', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('keeper_seeds', 'years_remaining')
    # ### end Alembic commands ###
