"""standing adjustments as deltas

Revision ID: 50cce1efc367
Revises: 6729772df0ae
Create Date: 2026-06-07 22:49:51.599094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50cce1efc367'
down_revision: Union[str, Sequence[str], None] = '6729772df0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing_adjustments', sa.Column('total_delta', sa.Integer(), server_default='0', nullable=False))
    op.add_column('standing_adjustments', sa.Column('points_for_delta', sa.Integer(), server_default='0', nullable=False))
    op.add_column('standing_adjustments', sa.Column('gameweek', sa.Integer(), nullable=True))
    op.drop_column('standing_adjustments', 'old_value')
    op.drop_column('standing_adjustments', 'new_value')
    op.drop_column('standing_adjustments', 'field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing_adjustments', sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('standing_adjustments', sa.Column('new_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('standing_adjustments', sa.Column('old_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('standing_adjustments', 'gameweek')
    op.drop_column('standing_adjustments', 'points_for_delta')
    op.drop_column('standing_adjustments', 'total_delta')
    # ### end Alembic commands ###
