"""season history + manager honors

Revision ID: 55ede5bfef86
Revises: f5bcb9332235
Create Date: 2026-06-07 20:48:03.313410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ede5bfef86'
down_revision: Union[str, Sequence[str], None] = 'f5bcb9332235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_honors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('manager_name', sa.String(), nullable=False),
    sa.Column('titles', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cups', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'manager_name', name='uq_honors_league_manager')
    )
    op.create_index(op.f('ix_manager_honors_league_id'), 'manager_honors', ['league_id'], unique=False)
    op.create_table('season_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('league_winner', sa.String(), nullable=True),
    sa.Column('cup_winner', sa.String(), nullable=True),
    sa.Column('pup_winner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'year', name='uq_season_history_league_year')
    )
    op.create_index(op.f('ix_season_history_league_id'), 'season_history', ['league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_history_league_id'), table_name='season_history')
    op.drop_table('season_history')
    op.drop_index(op.f('ix_manager_honors_league_id'), table_name='manager_honors')
    op.drop_table('manager_honors')
    # ### end Alembic commands ###
