"""trade notes

Revision ID: 6729772df0ae
Revises: ae8290cd26e8
Create Date: 2026-06-07 22:47:19.650969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6729772df0ae'
down_revision: Union[str, Sequence[str], None] = 'ae8290cd26e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('manager_a', sa.String(), nullable=True),
    sa.Column('gives_a', sa.Text(), nullable=True),
    sa.Column('manager_b', sa.String(), nullable=True),
    sa.Column('gives_b', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_notes_league_id'), 'trade_notes', ['league_id'], unique=False)
    op.create_index(op.f('ix_trade_notes_season'), 'trade_notes', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_notes_season'), table_name='trade_notes')
    op.drop_index(op.f('ix_trade_notes_league_id'), table_name='trade_notes')
    op.drop_table('trade_notes')
    # ### end Alembic commands ###
