"""historical standings

Revision ID: 6ed426ddcfd3
Revises: 55ede5bfef86
Create Date: 2026-06-07 20:54:13.641091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed426ddcfd3'
down_revision: Union[str, Sequence[str], None] = '55ede5bfef86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_standings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('manager_name', sa.String(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('points_for', sa.Integer(), nullable=True),
    sa.Column('h2h_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'year', 'rank', name='uq_hist_standing_year_rank')
    )
    op.create_index(op.f('ix_historical_standings_league_id'), 'historical_standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_historical_standings_year'), 'historical_standings', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_standings_year'), table_name='historical_standings')
    op.drop_index(op.f('ix_historical_standings_league_id'), table_name='historical_standings')
    op.drop_table('historical_standings')
    # ### end Alembic commands ###
