"""keeper seeds table + trade event_gw/fpl_trade_id

Revision ID: a2bae55c86ca
Revises: 35930d54c10a
Create Date: 2026-06-07 16:58:24.642969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bae55c86ca'
down_revision: Union[str, Sequence[str], None] = '35930d54c10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keeper_seeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('prior_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'player_id', name='uq_keeper_seed_mgr_player')
    )
    op.create_index(op.f('ix_keeper_seeds_league_id'), 'keeper_seeds', ['league_id'], unique=False)
    op.create_index(op.f('ix_keeper_seeds_manager_id'), 'keeper_seeds', ['manager_id'], unique=False)
    op.create_index(op.f('ix_keeper_seeds_player_id'), 'keeper_seeds', ['player_id'], unique=False)
    op.add_column('trades', sa.Column('event_gw', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('fpl_trade_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_trades_fpl_trade_id'), 'trades', ['fpl_trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_fpl_trade_id'), table_name='trades')
    op.drop_column('trades', 'fpl_trade_id')
    op.drop_column('trades', 'event_gw')
    op.drop_index(op.f('ix_keeper_seeds_player_id'), table_name='keeper_seeds')
    op.drop_index(op.f('ix_keeper_seeds_manager_id'), table_name='keeper_seeds')
    op.drop_index(op.f('ix_keeper_seeds_league_id'), table_name='keeper_seeds')
    op.drop_table('keeper_seeds')
    # ### end Alembic commands ###
