"""add standings table and manager league_entry id

Revision ID: a37f83c0d9f5
Revises: c434ee4988b0
Create Date: 2026-06-07 13:03:45.046935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37f83c0d9f5'
down_revision: Union[str, Sequence[str], None] = 'c434ee4988b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('last_rank', sa.Integer(), nullable=True),
    sa.Column('rank_sort', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('points_for', sa.Integer(), nullable=True),
    sa.Column('points_against', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('matches_won', sa.Integer(), nullable=True),
    sa.Column('matches_drawn', sa.Integer(), nullable=True),
    sa.Column('matches_lost', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'manager_id', name='uq_standing_league_manager')
    )
    op.create_index(op.f('ix_standings_league_id'), 'standings', ['league_id'], unique=False)
    op.create_index(op.f('ix_standings_manager_id'), 'standings', ['manager_id'], unique=False)
    op.add_column('managers', sa.Column('fpl_league_entry_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_managers_fpl_league_entry_id'), 'managers', ['fpl_league_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_fpl_league_entry_id'), table_name='managers')
    op.drop_column('managers', 'fpl_league_entry_id')
    op.drop_index(op.f('ix_standings_manager_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_league_id'), table_name='standings')
    op.drop_table('standings')
    # ### end Alembic commands ###
