"""player price + last_season_points

Revision ID: a6c9ada56d9f
Revises: 4e14166e5308
Create Date: 2026-06-07 22:00:24.795741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c9ada56d9f'
down_revision: Union[str, Sequence[str], None] = '4e14166e5308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('last_season_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'last_season_points')
    op.drop_column('players', 'price')
    # ### end Alembic commands ###
