"""league keepers_locked

Revision ID: ae8290cd26e8
Revises: 76c41c777e09
Create Date: 2026-06-07 22:42:57.998668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8290cd26e8'
down_revision: Union[str, Sequence[str], None] = '76c41c777e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('keepers_locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'keepers_locked')
    # ### end Alembic commands ###
