"""discovery_match_suggestions — proposed links, never applied ones

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-08-18

A discovery pick is free text until an admin links it to a real player
(`services.link_discovery_pick`), and that link is what gives the player his
four-year discovery keeper clock. Linking is manual on purpose. This table is the
queue that makes it tractable: the daily sync proposes candidates, a human decides.

Nothing here ever writes `DraftPick.player_id`. Even a 1.0 score is a suggestion —
two people share a name, and a wrong link is not detectable downstream, it just
quietly gives one manager another manager's keeper.

UNIQUE (draft_pick_id, player_id) is the whole idempotency story. The matcher runs
every day against a player pool that grows all season, so it must upsert rather than
accumulate duplicates; and because a REJECTED row stays in the table, a pair the
commissioner has already dismissed is never proposed again.

ON DELETE CASCADE on draft_pick_id is the only cascade in this schema, and is
deliberate: a suggestion is wholly derived from its pick and can be regenerated by
re-running the matcher, so it means nothing once the pick is deleted. Without it,
`services.delete_draft_pick` — written long before this table — would start failing on
a foreign key it has no reason to know about.

Deliberately NOT using `commissioner_alerts`: that table is dead code (defined, zero
readers and zero writers) and has neither a status column nor foreign keys, so it
cannot express "rejected, don't ask again", which is the requirement that matters.

HAND-WRITTEN, per the note in a1b2c3d4e5f6: `alembic revision --autogenerate` in this
repo emits DROP TABLE for the six v2_* tables that exist in the live database but not
in models.py.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

revision = "c3d4e5f6a7b8"
down_revision = "b2c3d4e5f6a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "discovery_match_suggestions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "draft_pick_id",
            UUID(as_uuid=True),
            sa.ForeignKey("draft_picks.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "player_id",
            UUID(as_uuid=True),
            sa.ForeignKey("players.id"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "draft_pick_id", "player_id", name="uq_discovery_suggestion_pick_player"
        ),
    )
    op.create_index(
        "ix_discovery_match_suggestions_draft_pick_id",
        "discovery_match_suggestions",
        ["draft_pick_id"],
    )
    op.create_index(
        "ix_discovery_match_suggestions_player_id",
        "discovery_match_suggestions",
        ["player_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_discovery_match_suggestions_player_id",
        table_name="discovery_match_suggestions",
    )
    op.drop_index(
        "ix_discovery_match_suggestions_draft_pick_id",
        table_name="discovery_match_suggestions",
    )
    op.drop_table("discovery_match_suggestions")
