"""initial schema

Revision ID: c434ee4988b0
Revises: 
Create Date: 2026-06-07 11:33:39.616677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c434ee4988b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fpl_league_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('draft_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_fpl_league_id'), 'leagues', ['fpl_league_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('current_team', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fpl_added_date', sa.Date(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_fpl_id'), 'players', ['fpl_id'], unique=True)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ok', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_kind'), 'sync_logs', ['kind'], unique=False)
    op.create_table('commissioner_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissioner_alerts_league_id'), 'commissioner_alerts', ['league_id'], unique=False)
    op.create_table('gameweeks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'number', name='uq_gameweek_league_number')
    )
    op.create_index(op.f('ix_gameweeks_league_id'), 'gameweeks', ['league_id'], unique=False)
    op.create_table('managers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('fpl_manager_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_fpl_manager_id'), 'managers', ['fpl_manager_id'], unique=False)
    op.create_index(op.f('ix_managers_league_id'), 'managers', ['league_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('start_gw', sa.Integer(), nullable=True),
    sa.Column('end_gw', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_league_id'), 'tournaments', ['league_id'], unique=False)
    op.create_table('draft_lottery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('pick_result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_lottery_league_id'), 'draft_lottery', ['league_id'], unique=False)
    op.create_index(op.f('ix_draft_lottery_manager_id'), 'draft_lottery', ['manager_id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_league_id'), 'draft_picks', ['league_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_manager_id'), 'draft_picks', ['manager_id'], unique=False)
    op.create_table('gameweek_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('gameweek_id', sa.UUID(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('player_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'gameweek_id', name='uq_gwpoints_manager_gameweek')
    )
    op.create_index(op.f('ix_gameweek_points_gameweek_id'), 'gameweek_points', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_gameweek_points_manager_id'), 'gameweek_points', ['manager_id'], unique=False)
    op.create_table('injury_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('start_gw', sa.Integer(), nullable=False),
    sa.Column('end_gw', sa.Integer(), nullable=True),
    sa.Column('replacement_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['replacement_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_list_manager_id'), 'injury_list', ['manager_id'], unique=False)
    op.create_index(op.f('ix_injury_list_player_id'), 'injury_list', ['player_id'], unique=False)
    op.create_table('keeper_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('validated_gw', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keeper_exceptions_league_id'), 'keeper_exceptions', ['league_id'], unique=False)
    op.create_index(op.f('ix_keeper_exceptions_manager_id'), 'keeper_exceptions', ['manager_id'], unique=False)
    op.create_index(op.f('ix_keeper_exceptions_player_id'), 'keeper_exceptions', ['player_id'], unique=False)
    op.create_table('rosters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('gameweek_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('keeper_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('original_year', sa.Integer(), nullable=True),
    sa.Column('is_keeper', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_discovery', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rosters_gameweek_id'), 'rosters', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_rosters_manager_id'), 'rosters', ['manager_id'], unique=False)
    op.create_index(op.f('ix_rosters_player_id'), 'rosters', ['player_id'], unique=False)
    op.create_table('tournament_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('manager_a', sa.UUID(), nullable=False),
    sa.Column('manager_b', sa.UUID(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['manager_a'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['manager_b'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_matches_tournament_id'), 'tournament_matches', ['tournament_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('from_manager', sa.UUID(), nullable=False),
    sa.Column('to_manager', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('draft_pick', sa.String(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_manager'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_manager'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_league_id'), 'trades', ['league_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('gameweek_id', sa.UUID(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_gameweek_id'), 'transactions', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_transactions_league_id'), 'transactions', ['league_id'], unique=False)
    op.create_index(op.f('ix_transactions_manager_id'), 'transactions', ['manager_id'], unique=False)
    op.create_index(op.f('ix_transactions_player_id'), 'transactions', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_player_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_manager_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_league_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gameweek_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_trades_league_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_tournament_matches_tournament_id'), table_name='tournament_matches')
    op.drop_table('tournament_matches')
    op.drop_index(op.f('ix_rosters_player_id'), table_name='rosters')
    op.drop_index(op.f('ix_rosters_manager_id'), table_name='rosters')
    op.drop_index(op.f('ix_rosters_gameweek_id'), table_name='rosters')
    op.drop_table('rosters')
    op.drop_index(op.f('ix_keeper_exceptions_player_id'), table_name='keeper_exceptions')
    op.drop_index(op.f('ix_keeper_exceptions_manager_id'), table_name='keeper_exceptions')
    op.drop_index(op.f('ix_keeper_exceptions_league_id'), table_name='keeper_exceptions')
    op.drop_table('keeper_exceptions')
    op.drop_index(op.f('ix_injury_list_player_id'), table_name='injury_list')
    op.drop_index(op.f('ix_injury_list_manager_id'), table_name='injury_list')
    op.drop_table('injury_list')
    op.drop_index(op.f('ix_gameweek_points_manager_id'), table_name='gameweek_points')
    op.drop_index(op.f('ix_gameweek_points_gameweek_id'), table_name='gameweek_points')
    op.drop_table('gameweek_points')
    op.drop_index(op.f('ix_draft_picks_manager_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_league_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_draft_lottery_manager_id'), table_name='draft_lottery')
    op.drop_index(op.f('ix_draft_lottery_league_id'), table_name='draft_lottery')
    op.drop_table('draft_lottery')
    op.drop_index(op.f('ix_tournaments_league_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_managers_league_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_fpl_manager_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_gameweeks_league_id'), table_name='gameweeks')
    op.drop_table('gameweeks')
    op.drop_index(op.f('ix_commissioner_alerts_league_id'), table_name='commissioner_alerts')
    op.drop_table('commissioner_alerts')
    op.drop_index(op.f('ix_sync_logs_kind'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_players_fpl_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_leagues_fpl_league_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
