"""cup matches

Revision ID: f573357ce3ed
Revises: d89b6069c1c9
Create Date: 2026-06-07 21:46:57.122226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f573357ce3ed'
down_revision: Union[str, Sequence[str], None] = 'd89b6069c1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cup_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('bracket', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('manager_label', sa.String(), nullable=True),
    sa.Column('gw1', sa.Integer(), nullable=True),
    sa.Column('gw2', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cup_matches_league_id'), 'cup_matches', ['league_id'], unique=False)
    op.create_index(op.f('ix_cup_matches_season'), 'cup_matches', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cup_matches_season'), table_name='cup_matches')
    op.drop_index(op.f('ix_cup_matches_league_id'), table_name='cup_matches')
    op.drop_table('cup_matches')
    # ### end Alembic commands ###
