"""manager display_name (person)

Revision ID: f5bcb9332235
Revises: 22a39fde8712
Create Date: 2026-06-07 20:21:01.860709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bcb9332235'
down_revision: Union[str, Sequence[str], None] = '22a39fde8712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'display_name')
    # ### end Alembic commands ###
